version: '3'

services:
  spring-boot-rest-api-app:
    image: spring-boot-rest-docker-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /data/docker-spring-boot-app